### ISSUE TITLE
relocation R_X86_64_32S against `AddonsCore_Init' Error

### ISSUE THREAD

**Issue by bvr44u** [sbusard/pynusmv#11]
Hi,
I was building the pynusmv. While executing ./build_libnumsv.sh, I got the following error.

/usr/bin/ld: nusmv/main.o: relocation R_X86_64_32S against `AddonsCore_Init' can not be used when making a shared object; recompile with -fPIC
nusmv/main.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

Can you please help me out in this.

**Comment by sbusard** [comment]
Hello,

Sorry for the delay.

How did you build pynusmv? The error suggests to recompile NuSMV with `-fPIC`, but it's already done (in src/Makefile).

Also, what platform are you working on? You maybe don't need to build pynusmv, as it is already compiled for you on some platforms. You can directly try `pip3 install pynusmv`.

Finally, you can try getting some help on the official PyNuSMV repository: https://github.com/LouvainVerificationLab/pynusmv

**Comment by bvr44u** [comment]
Hi,
I followed the same steps as mentioned in the read.me. I din't tried using the -fPIC.
I am using Ubuntu 16.04, with Python 3.5.

**Comment by sbusard** [comment]
Which part of the README did you followed? Simply executing `make` in the root directory should build everything.

I see there is an error in the README file at Line 85 (https://github.com/sbusard/pynusmv/blob/master/README#L85): some flags are missing. This could be the reason why you get that error message. So if you followed these detailed steps (instead of just executing `make` in the root directory), then you should replace
`./configure`
with
`./configure CFLAGS="-g -O2 -fPIC"`

**Comment by sbusard** [comment]
By the way, if you just want to **use** pynusmv (not modify it), you can try `pip install pynusmv`: you will directly get access to pre-compiled versions, and will have nothing else to do before using pynusmv.

**Comment by bvr44u** [comment]
Sorry for the delay. It somehow worked out.
Thanks for the help.
